config/routes.rb
Rails.application.routes.draw do
 resources :feeds 
  get 'entries/index'
get 'entries/show'
    root 'entries#index'
    
# This line mounts Monologue's routes at the root of your application.
# This means, any requests to URLs such as /my-post, will go to Monologue::PostsController.
# If you would like to change where this engine is mounted, simply change the :at option to something different.
#
# We ask that you don't use the :as option here, as Monologue relies on it being the default of "monologue"
mount Monologue::Engine, at: '/articles' # or whatever path, be it "/blog" or "/monologue"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :feed
    
      
  before_create :too_many

  private
    def too_many
      Entry.first.destroy if Entry.count > 100
    end
end

app/models/feed.rb
class Feed < ApplicationRecord
    has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_feed, only: :index


  def index
    @entries = Entry.all.order('published desc').limit(50)
   @buzzposts = Entry.where(:feed_id => 1).order('published desc').limit(10)
   @thoughts = Entry.where(:feed_id => 2).order('published desc').limit(10)
   @chives = Entry.where(:feed_id => 3).order('published desc').limit(10)
   @ups = Entry.where(:feed_id => 4).order('published desc').limit(10)
   @posts = Monologue::Post.published
  end

  def show
    @entry = Entry.find(params[:id])
  end

  private
  def set_feed
   
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(feed) do |f| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.url %></td>
        <td><%= feed.description %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feed.description %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/monologue/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monologue</title>
  <%= stylesheet_link_tag    "monologue/admin/application" %>
  <%= javascript_include_tag "monologue/admin/application" %>
  <%= csrf_meta_tags %>
</head>
<body> 
  <% if monologue_current_user %>
    <%= render "layouts/monologue/admin/nav_bar" %>
  <% end %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}", class: (name == 'notice' ? "alert alert-info" : "alert alert-error") %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/monologue/admin/_nav_bar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container" data-monologue="nav-bar">
      <%= link_to "Monologue", admin_path, class: "brand" %>
      <ul class="nav pull-left" data-monologue="nav-bar-left">
        <%= activable_li_tag_with_link t(".add_a_monologue"), new_admin_post_path %>
        <%= activable_li_tag_with_link t(".list_monologues"), admin_posts_path, admin_path %>
        <%= activable_li_tag_with_link t(".comments"), admin_comments_path %>
      </ul>

      <ul class="nav pull-right" data-monologue="nav-bar-right">
        <%= activable_li_tag_with_link t(".users"), admin_users_path %>
        <li id="fat-menu" class="dropdown">
          <a href="#" id="settings" data-toggle="dropdown"><%= t(".settings") %> <b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="settings">
            <li><%= link_to t(".edit_user_info"), edit_admin_user_path(monologue_current_user)%></li>
          </ul>
        </li>
        <li><%= link_to t(".log_out"), admin_logout_path %></li>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/monologue/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
  <%= render 'layouts/monologue/application/head' %>
</head>
<body>
  <div class="container">
    <header class="main-header sixteen columns clearfix">
      <%= rss_icon %>
      <h1><a href="<%= root_path %>"><%=Monologue::Config.site_name%></a></h1>
      <h2><%=Monologue::Config.site_subtitle%></h2>
      <%= render partial: "layouts/monologue/application/social_icons" %>
    </header>

    <div class="content twelve columns">
      <% flash.each do |name, msg| %>
        <div class="flash-notice">
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>

      <%= render 'layouts/monologue/application/sidebar' %>
  </div>
  <% if content_for?(:footer) %>
    <footer>
      <%= yield :footer %>
    </footer>
  <% end %>
  <%= render 'layouts/monologue/application/disqus' %>
  <%= render 'layouts/monologue/application/gauge_analytics' %>
</body>
</html>

app/views/layouts/monologue/application/_disqus.html.erb
<script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = '<%= Monologue::Config.disqus_shortname%>'; // required: replace example with your forum shortname

  <% if Rails.env.development?  %>
  var disqus_developer = 1; // developer mode is on
  <% end %>


  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
  }());
</script>

app/views/layouts/monologue/application/_disqus_embed.html.erb
<script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = '<%= Monologue::Config.disqus_shortname%>'; // required: replace example with your forum shortname

  <% if Rails.env.development?  %>
  var disqus_developer = 1; // developer mode is on
  <% end %>

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function () {
    var dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>

app/views/layouts/monologue/application/_fb_open_graph.html.erb
<meta property="og:title" content="<%= monologue_accurate_title %>"/>
<meta property="og:type" content="<%= controller.action_name == "show" ? "article" : "blog" %>"/>
<meta property="og:url" content="<%= request.protocol %><%= request.host_with_port %><%= request.path.gsub("//","/") %>"/>
<meta property="og:site_name" content="<%= Monologue::Config.site_name %>"/>
<% if Monologue::Config.facebook_logo%>
   <meta property="og:image" content="<%= absolute_image_url(image_path(Monologue::Config.facebook_logo)) %>" />
<% end  %>

app/views/layouts/monologue/application/_gauge_analytics.html.erb
<% unless Monologue::Config.gauge_analytics_site_id.nil? %>
  <script type="text/javascript">
    var _gauges = _gauges || [];
    (function() {
      var t   = document.createElement('script');
      t.type  = 'text/javascript';
      t.async = true;
      t.id    = 'gauges-tracker';
      t.setAttribute('data-site-id', '<%= Monologue::Config.gauge_analytics_site_id %>');
      t.src = '//secure.gaug.es/track.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(t, s);
    })();
  </script>
<% end %>

app/views/layouts/monologue/application/_google_analytics.html.erb
<% unless Monologue::Config.google_analytics_id.nil? %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '<%= Monologue::Config.google_analytics_id %>']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
<% end %>

app/views/layouts/monologue/application/_head.html.erb
<%= render "layouts/monologue/application/title" %>
<meta charset="utf-8" />
<%= render "layouts/monologue/application/meta_description" %>
<%= render "layouts/monologue/application/fb_open_graph" %>
<%= render "layouts/monologue/application/twitter_cards" %>
<meta name="keyword" content="<%=Monologue::Config.meta_keyword%>">

<meta http-equiv="content-type" content="text/html;charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<%= stylesheet_link_tag    "monologue/blog/application" %>
<%= javascript_include_tag "monologue/blog/application" %>

<!-- Mobile Specific Metas
================================================== -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<%= rss_head_link %>
<%= render "layouts/monologue/application/google_analytics" %>

app/views/layouts/monologue/application/_meta_description.html.erb
<meta name="description" content="<%= content_for?(:meta_description) ? yield(:meta_description) : Monologue::Config.meta_description  %>" />

app/views/layouts/monologue/application/_sidebar.html.erb
<% if Monologue::Config.sidebar %>
<aside class="sidebar four columns">
   <% Monologue::Config.sidebar.each do |ext| %>
     <%= render partial: "monologue/sidebar/#{ext}" %>
   <% end %>
</aside>
<% end %>

app/views/layouts/monologue/application/_social_icons.html.erb
<%= facebook_icon %>
<%= googleplus_icon %>
<%= linkedin_icon %>
<%= twitter_icon %>
<%= github_icon %>

app/views/layouts/monologue/application/_title.html.erb
<title>
  <%= monologue_accurate_title %>
</title>

app/views/layouts/monologue/application/_twitter_cards.html.erb
<meta name="twitter:card" content="summary">
<% if Monologue::Config.twitter_username %>
  <meta name="twitter:site" content="<%= Monologue::Config.twitter_username %>">
<% end %>
<meta name="twitter:url" content="<%= request.protocol %><%= request.host_with_port %><%= request.path.gsub("//","/") %>">
<meta name="twitter:title" content="<%= monologue_accurate_title %>">
<meta name="twitter:description" content="<%= content_for?(:meta_description) ? yield(:meta_description) : Monologue::Config.meta_description  %>">

app/views/monologue/admin/comments/show.html.erb
<div id="recentcomments" class="dsq-widget">
  <h1 class="dsq-widget-title"><%= t(".recent_comments") %></h1>
  <script type="text/javascript" src="//<%= Monologue::Config.disqus_shortname%>.disqus.com/recent_comments_widget.js?num_items=20&hide_avatars=0&avatar_size=48&excerpt_length=500"></script>
</div>

app/views/monologue/admin/posts/_form.html.erb
<%= post.error_messages %>
<%= post.text_field :title, label:  t(".title"), class:  "span6" %>
<%= post.text_area :content, label:  t(".content"), class:  "span12 ckeditor", id: "post_content" %>
<%= post.text_field :url, label:  raw(t(".url.caption", default_url: "#{DateTime.now.year}/#{t(".url.generated_title")}", root: monologue.root_path)) %>
<%= post.text_field :published_at, label:  t(".published_at"), data: {datepicker: "datepicker"}, value: post.object.published_at.nil? ? "" : post.object.published_at.strftime("%Y-%m-%d") %>
<%= post.text_field :tag_list, label:  raw(t(".tags")) %>
<%= post.check_box :published, label:  t(".published") %>

<div class="form-actions">
  <%= post.button t(".save"), class:  "btn btn-large btn-primary" %> 
  <%= post.button t(".preview"), class: "btn btn-large", type: "button", value: "preview"%>
</div>

<div class="post-preview modal-backdrop hide" data-url="<%=admin_post_preview_url%>" data-toggle="post-preview" data-trigger="button[value='preview']">
  <div class="post-preview-inner">
    <div class="navbar pull-right">
      <div class="navbar-inner">
        <span class="brand"><%=t(".preview")%></span> 
        <a class="btn btn-primary pull-right" data-dismiss="post-preview"><%=t(".close")%></a>
      </div>
    </div>
  </div>
  <iframe src="" name="preview"></iframe>
</div>

<script>
  if($.fn.datepicker.defaults_<%= I18n.locale %>){
    $.fn.datepicker.defaults = $.fn.datepicker.defaults_<%= I18n.locale %>;
  }
  $("#post_tag_list").select2({tags: <%= Monologue::Tag.all.map{|t| t.name }.to_json.html_safe %> });
</script>

app/views/monologue/admin/posts/_pagination.html.erb
<div id="pagination">
  <% if @posts.total_pages > 1 && @posts.total_pages != @page.to_i %>
    <%= link_to t(".older_posts"), admin_posts_page_path(@page.to_i+1), class: "older_posts" %>
  <% end %>

  <% if @posts.total_pages > 1 && @page.to_i > 1 %>
    <%= link_to t(".newer_posts"), admin_posts_page_path(@page.to_i-1), class: "newer_posts" %>
  <% end %>
</div>

app/views/monologue/admin/posts/edit.html.erb
<h1><%= t(".header") %> "<%= @post.title %>"</h1>
<%= monologue_admin_form_for ["admin", @post], method: :put do |post| %>
  <%= render partial: 'form', locals: {post: post} %>
<% end %>

app/views/monologue/admin/posts/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= t(".title")%></th>
      <th><%= t(".status")%></th>
      <th><%= t(".author")%></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post|%>
      <tr>
        <td><%= link_to post.title, edit_admin_post_path(post) %></td>
        <td><span class="label label-<%= post.published ? "success" : "important" %>"><%= post.published ? t(".published") : t(".not_published") %></span></td>
        <td><span><%= post.user.name %></span> </td>
        <td><%= link_to t(".edit"), edit_admin_post_path(post), class: "btn btn-small" %></td>
        <td><%= link_to t(".delete"), [:admin, post],data: {confirm: 'Are you sure?'}, method: :delete, class: "btn btn-small btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @page %>
  <%= render partial: "pagination" %>
<% end %>

app/views/monologue/admin/posts/new.html.erb
<h1><%= t(".header") %></h1>
<%= monologue_admin_form_for ["admin", @post] do |post| %>
  <%= render partial: 'form', locals: {post: post} %>
<% end %>

app/views/monologue/admin/users/_form.html.erb
<%= user.error_messages %>
<%= user.text_field :name, label:  t(".name"), class:  "span6" %>
<%= user.text_field :email, label:  t(".email"), class:  "span6" %>
<%= user.password_field :password, label:  t(".password"), class:  "span6" %>
<%= user.password_field :password_confirmation, label:  t(".password_confirmation"), class:  "span6" %>

app/views/monologue/admin/users/edit.html.erb
<h1><%= t(".header") %></h1>
<%= monologue_admin_form_for [:admin, @user], method: :put do |user| %>
  <%= render :partial => 'form', :locals => { :user => user } %>
  <%= user.submit t(".save"), class:  "btn btn-large btn-primary" %>
<% end %>

app/views/monologue/admin/users/index.html.erb
<h2><%= link_to t(".create"), new_admin_user_path, class: "btn btn-success" %></h2>

<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th><%= t(".name") %></th>
    <th><%= t(".email") %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to t(".edit"), edit_admin_user_path(user), class: "btn btn-small" %></td>
      <td>
        <% if monologue_current_user.can_delete?(user) %>
          <%= link_to t(".delete"), [:admin, user], data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-small btn-danger" %>
        <% else %>
          <a href="#" class="btn btn-small btn-danger disabled"><%= t(".delete") %></a>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/monologue/admin/users/new.html.erb
<h1><%= t(".header") %></h1>
<%= monologue_admin_form_for [:admin, @user], method: :post do |user| %>
  <%= render :partial => 'form', :locals => { :user => user } %>
  <%= user.submit t(".create"), class:  "btn btn-large btn-primary" %>
<% end %>

app/views/monologue/posts/404.html.erb
<% content_for :title do %>
  <%= t(".title") %>
<% end %>

<article>
  <header><h1><%= t(".title") %></h1></header>
  <p><%= t(".message") %></p>
</article>

app/views/monologue/posts/_pagination.html.erb
<div id="pagination">
  <% if @posts.total_pages > 1 && @posts.total_pages != @page.to_i %>
    <%= link_to t(".older_posts"), posts_page_path(@page.to_i+1), class: "older_posts" %>
  <% end %>

  <% if @posts.total_pages > 1 && @page.to_i > 1 %>
    <%= link_to t(".newer_posts"), posts_page_path(@page.to_i-1), class: "newer_posts" %>
  <% end %>
</div>

app/views/monologue/posts/_post.html.erb
<section data-tags="<%= post.tags.map(&:name).join(' ') %>">
  <%= render partial: 'monologue/posts/post_header', locals: {post: post} %>

  <div class="content" data-monologue="content">
    <%= truncate_html(post.content, length: Monologue::Config.preview_size, omission: '...') %>
  </div>

  <div class="tags" data-monologue="tags">
    <%= render post.tags %>
  </div>
  <%= link_to t(".readmore"), post.full_url, class: "button" %>
</section>

app/views/monologue/posts/_post_header.html.erb
<header class="post-header">
  <h1><%= link_to post.title, post.full_url %></h1>
  <div class="posted">
    <span data-monologue="time">
      <time datetime="<%= post.published_at %>">
        <%= I18n.localize(post.published_at.to_date, format: :long) %>
      </time>
    </span>
    <span data-monologue="user">
      <%= post.user.name %>
    </span>
    <span data-monologue="disqus">
      <a href="<%= post.full_url + "#disqus_thread" %>"></a>
    </span>
  </div>
</header>

app/views/monologue/posts/_social_sharing.html.erb
<div class="monologue-social-sharing" data-monologue="monologue-social-sharing">
  <span class="social-tagline"><%= t('.tagline') %></span>
  <ul id="social-share">
    <li id="google-plus">
      <%= render :partial => 'monologue/posts/social/pinterest' %>
    </li>
    <li id="twitter">
       <%= render :partial => 'monologue/posts/social/twitter' %>
    </li>
    <li id="google-plus">
        <%= render :partial => 'monologue/posts/social/gplus' %>
     </li>
    <li id="facebook">
      <%= render :partial => 'monologue/posts/social/facebook' %>
    </li>
  </ul>
</div>

app/views/monologue/posts/index.html.erb
<%= render @posts %>

<% if @page %>
	<%= render partial: "pagination" %>
<% end %>

app/views/monologue/posts/show.html.erb
<% content_for :title do %>
  <%= @post.title %>
<% end %>

<% content_for :meta_description do %>
  <%= truncate(strip_tags(@post.content), length: 155) %>
<% end %>

<article>
  <%= render partial: 'monologue/posts/post_header', locals: {post: @post }%>
  <div class="content" data-monologue="content">
    <%= raw @post.content %>
  </div>

	<div class="tags" data-monologue="tags">
    <%= render @post.tags %>
  </div>

  <%= render "monologue/posts/social_sharing" %>

  <div id="disqus_thread"></div>
  <%= render 'layouts/monologue/application/disqus_embed' %>
  <noscript>Please enable JavaScript to view the comments.</noscript>
</article>

app/views/monologue/posts/social/_facebook.html.erb
<% if Monologue::Config.facebook_app_id.present? %>
  <div id="fb-root"></div>
  <script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/<%= Monologue::Config.facebook_like_locale || "en_US" %>/all.js#xfbml=1&appId=<%= Monologue::Config.facebook_app_id %>";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <div class="fb-like" data-send="false" data-width="450" data-show-faces="false"></div>
<% end %>

app/views/monologue/posts/social/_gplus.html.erb
<div id="google-plus">
  <g:plusone size="medium"></g:plusone>

  <script type="text/javascript">
    window.___gcfg = {lang: '<%=Monologue::Config.google_plusone_locale || "en" %>'};

    (function () {
      var po = document.createElement('script');
      po.type = 'text/javascript';
      po.async = true;
      po.src = 'https://apis.google.com/js/plusone.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(po, s);
    })();
  </script>
</div>

app/views/monologue/posts/social/_pinterest.html.erb
<% if Monologue::Config.use_pinterest.presence %>
<%= link_to"Pin It",
             "http://pinterest.com/pin/create/button/?url=#{@post.url}",
             :class => "pin-it-button",
             "count-layout" => "none" %>

<script type="text/javascript">
  (function (d) {
    var f = d.getElementsByTagName('SCRIPT')[0], p = d.createElement('SCRIPT');
    p.type = 'text/javascript';
    p.async = true;
    p.src = '//assets.pinterest.com/js/pinit.js';
    f.parentNode.insertBefore(p, f);
  }(document));
</script>
<% end %>

app/views/monologue/posts/social/_twitter.html.erb
<% if Monologue::Config.twitter_username.present? %>
  <a href="https://twitter.com/share" class="twitter-share-button"
     data-lang="<%= Monologue::Config.twitter_locale || "en" %>"
     data-url="<%= request.protocol %><%= request.host_with_port %><%= request.path.gsub("//", "/") %>"
     data-via="<%= Monologue::Config.twitter_username %>"
     data-text="<%= @post.title %>"
     data-count="horizontal">Tweet</a>

  <script>!function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (!d.getElementById(id)) {
      js = d.createElement(s);
      js.id = id;
      js.src = "//platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);
    }
  }(document, "script", "twitter-wjs");</script>
<% end %>

app/views/monologue/sidebar/_categories.html.erb
<%= sidebar_section_for(t(".title")) do %>
   <ul>
     <% @tags.each do |tag| %>
       <li id="tag"><%=link_to "#{tag.name} (#{tag.frequency})", tag_url(tag) %> </li>
     <% end %>
   </ul>
 <% end %>

app/views/monologue/sidebar/_latest_posts.html.erb
<%= sidebar_section_for(t(".title")) do  %>
  <ul>
    <% @recent_posts.each do |post| %>
      <li><%= link_to post.title, post.full_url %></li>
    <% end %>
  </ul>
<% end %>